# Generated by Django 2.2.7 on 2019-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191121_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
