# Generated by Django 2.2.7 on 2019-11-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20191125_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='yazar'),
            preserve_default=False,
        ),
    ]
